# Homework 4.ipynb

# Purpose

This homework will start us into NumPy.  Remember that NumPy is used for matrix calculations as a primary objective, and will apply directly to Pandas in the long run.  This homework will focus on ..

# Required Hand-in

One notebook will be required.  Please note that the homework this time will be more strict for the naming/format requirements.  Please do not use this notebook directly and fill in the blanks, for the final version.  Instead, do that for your draft, make sure you get the right answer, and then create your own notebook, with your own logic.  Include the sections that you extended upon.  Look for opportunities to use functions or to make more generic ways to make your code more reusable.  These expansion opportunities will count toward the format/readability portion of the grade (30%)

In [1]:
import numpy as np
import numpy.random as rnd


# Part 1, generating a random matrix

Remember that generating a random matrix is within numpy here.  Also note that their algorithm can provide different values than we'd get in the way we've done it in previous homeworks.

Please generate 2 matrices, 10x7 each with numbers you choose (I don't suggest too large of numbers, but you can go as high as you're comfortable reading). Conceptually speaking, this'll be some measurement chosen every day, or 10 weeks.  The names of your variable would depend on what random values you decide to use.

In [2]:
# Seed

array([[9, 9, 3, 3, 9, 8, 6],
       [5, 7, 5, 3, 3, 6, 5],
       [9, 9, 9, 7, 7, 7, 3],
       [9, 7, 8, 4, 6, 7, 5],
       [8, 8, 8, 5, 6, 9, 9],
       [8, 9, 3, 5, 7, 4, 6],
       [9, 8, 6, 4, 9, 5, 3],
       [5, 6, 7, 5, 6, 3, 5],
       [7, 3, 9, 6, 3, 7, 6],
       [9, 5, 9, 5, 8, 4, 4]])

array([[126, 115, 113, 124, 123, 129, 123],
       [122, 127, 129, 129, 133, 126, 117],
       [122, 132, 110, 122, 133, 127, 112],
       [115, 112, 111, 116, 122, 112, 125],
       [111, 111, 124, 114, 125, 120, 115],
       [122, 129, 123, 115, 124, 133, 128],
       [121, 132, 112, 111, 119, 131, 122],
       [119, 128, 121, 131, 129, 124, 127],
       [123, 112, 134, 131, 110, 122, 122],
       [132, 131, 123, 133, 129, 115, 111]])

# Part 2, selecting elements
We're going to select both individual elements, as well as ranges.  Remember that range selection is very similar between base python and NumPy
# Part 2a - Single Elements

In [5]:
# Output the very first element on your first array

9

In [6]:
# Output the very last element on your first array
# Remember that we can "look back", so xxx[10,7] is wrong
# We don't want to be tied to assumptions on the size

4

In [7]:
# Reading as we would as humans (1-10), please return the element that is on the 5th week, 2nd day on the first array
# Remember your code will reference based off index 0

8

# Part 2b - Slices of elements

In [8]:
# Reading as we would as humans (1-10), please return the values that happened on the 7th week (full week)

array([9, 8, 6, 4, 9, 5, 3])

In [9]:
# Starting the week on a sunday (day 1), return all the weekday (days 2-6) elements that are on the 7th week.

array([8, 6, 4, 9, 5])

One special note about the following request.  You can pass in an array as part of the selector, to pick specific items.  For example, see what I have below.  I anonymized the variable name, but it's for the first array.

In [10]:
XXXXX  # Just so we don't have to scroll up

array([[9, 9, 3, 3, 9, 8, 6],
       [5, 7, 5, 3, 3, 6, 5],
       [9, 9, 9, 7, 7, 7, 3],
       [9, 7, 8, 4, 6, 7, 5],
       [8, 8, 8, 5, 6, 9, 9],
       [8, 9, 3, 5, 7, 4, 6],
       [9, 8, 6, 4, 9, 5, 3],
       [5, 6, 7, 5, 6, 3, 5],
       [7, 3, 9, 6, 3, 7, 6],
       [9, 5, 9, 5, 8, 4, 4]])

In [11]:
# Selecting (as we would count) rows 2, and 8
XXXXX[[1, 7]]

array([[5, 7, 5, 3, 3, 6, 5],
       [5, 6, 7, 5, 6, 3, 5]])

In [12]:
# Selecting (as we would count) rows 2, and 8, and columns 2 and 4
XXXXX[[1, 3],:][:,[1, 3]]

array([[7, 3],
       [7, 4]])

In [13]:
# This can also be written as...
XXXXX[np.ix_([1,3], [1,3])]

array([[7, 3],
       [7, 4]])

In [14]:
# Counting as humans count, please pull the 5th and 9th week, and the 2nd, and 6th days of your first array

array([[8, 9],
       [3, 7]])

In [15]:
# Counting as humans count, please pull the 3rd, 5th and 9th week, and the 3rd, and 6th, and 7th days of your first array

array([[9, 7, 3],
       [8, 9, 9],
       [9, 7, 6]])

# Part 2c - Slicing programmatically
We can programmatically pull elements, and this will help practice that

In [16]:
# Create a list of the odd weeks (as we count).  Do this programmatically
# hint: you can use filter and range (be mindful of the definition of range, and what it includes at the end)

[1, 3, 5, 7, 9]

In [17]:
# Create a list of the odd days (as we count).  Do this programmatically
# hint: you can use filter and range (be mindful of the definition of range, and what it includes at the end)

[1, 3, 5, 7]

In [18]:
# For your first array, pull out the odd weeks.  Remember python starts with 0 as the index

array([[9, 9, 3, 3, 9, 8, 6],
       [9, 9, 9, 7, 7, 7, 3],
       [8, 8, 8, 5, 6, 9, 9],
       [9, 8, 6, 4, 9, 5, 3],
       [7, 3, 9, 6, 3, 7, 6]])

In [19]:
# For your first array, pull out the odd days (keep all weeks).  Remember Python starts with 0 as the index

array([[9, 3, 9, 6],
       [5, 5, 3, 5],
       [9, 9, 7, 3],
       [9, 8, 6, 5],
       [8, 8, 6, 9],
       [8, 3, 7, 6],
       [9, 6, 9, 3],
       [5, 7, 6, 5],
       [7, 9, 3, 6],
       [9, 9, 8, 4]])

In [20]:
# Now combine the logic.  Odd weeks and odd days only

array([[9, 3, 9, 6],
       [9, 9, 7, 3],
       [8, 8, 6, 9],
       [9, 6, 9, 3],
       [7, 9, 3, 6]])

# Part 3 - Matrix Calculations

In [21]:
# Multiply your first matrix by your second matrix.
# Don't overcomplicate it, you don't need to iterate

array([[1134, 1035,  339,  372, 1107, 1032,  738],
       [ 610,  889,  645,  387,  399,  756,  585],
       [1098, 1188,  990,  854,  931,  889,  336],
       [1035,  784,  888,  464,  732,  784,  625],
       [ 888,  888,  992,  570,  750, 1080, 1035],
       [ 976, 1161,  369,  575,  868,  532,  768],
       [1089, 1056,  672,  444, 1071,  655,  366],
       [ 595,  768,  847,  655,  774,  372,  635],
       [ 861,  336, 1206,  786,  330,  854,  732],
       [1188,  655, 1107,  665, 1032,  460,  444]])

In [22]:
# Divide your first matrix by your second matrix.
# Again, don't overcomplicate it

array([[0.07142857, 0.07826087, 0.02654867, 0.02419355, 0.07317073,
        0.0620155 , 0.04878049],
       [0.04098361, 0.05511811, 0.03875969, 0.02325581, 0.02255639,
        0.04761905, 0.04273504],
       [0.07377049, 0.06818182, 0.08181818, 0.05737705, 0.05263158,
        0.05511811, 0.02678571],
       [0.07826087, 0.0625    , 0.07207207, 0.03448276, 0.04918033,
        0.0625    , 0.04      ],
       [0.07207207, 0.07207207, 0.06451613, 0.04385965, 0.048     ,
        0.075     , 0.07826087],
       [0.06557377, 0.06976744, 0.02439024, 0.04347826, 0.05645161,
        0.03007519, 0.046875  ],
       [0.07438017, 0.06060606, 0.05357143, 0.03603604, 0.07563025,
        0.03816794, 0.02459016],
       [0.04201681, 0.046875  , 0.05785124, 0.03816794, 0.04651163,
        0.02419355, 0.03937008],
       [0.05691057, 0.02678571, 0.06716418, 0.04580153, 0.02727273,
        0.05737705, 0.04918033],
       [0.06818182, 0.03816794, 0.07317073, 0.03759398, 0.0620155 ,
        0.03478261, 0.0

In [23]:
# Multiply each element in your first matrix by 2

array([[18, 18,  6,  6, 18, 16, 12],
       [10, 14, 10,  6,  6, 12, 10],
       [18, 18, 18, 14, 14, 14,  6],
       [18, 14, 16,  8, 12, 14, 10],
       [16, 16, 16, 10, 12, 18, 18],
       [16, 18,  6, 10, 14,  8, 12],
       [18, 16, 12,  8, 18, 10,  6],
       [10, 12, 14, 10, 12,  6, 10],
       [14,  6, 18, 12,  6, 14, 12],
       [18, 10, 18, 10, 16,  8,  8]])

# Part 4 - Matrix Calculations pt 2
We can create our own functions and apply them to a matrix.  This is from the np.vectorize which you can read about here:
https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html

In [24]:
# Look at your first matrix.  What's a good middle value for what you have, for example, my numbers are 3-8 for range so I'll pick 5 as the threshold.

array([[9, 9, 3, 3, 9, 8, 6],
       [5, 7, 5, 3, 3, 6, 5],
       [9, 9, 9, 7, 7, 7, 3],
       [9, 7, 8, 4, 6, 7, 5],
       [8, 8, 8, 5, 6, 9, 9],
       [8, 9, 3, 5, 7, 4, 6],
       [9, 8, 6, 4, 9, 5, 3],
       [5, 6, 7, 5, 6, 3, 5],
       [7, 3, 9, 6, 3, 7, 6],
       [9, 5, 9, 5, 8, 4, 4]])

In [25]:
# Write a vectorize function that will check if the incoming value is > than the middle (in my case 5).  If it is, return True, if not, return False.  Apply this function to your first matrix and assign to a variable

array([[ True,  True, False, False,  True,  True,  True],
       [False,  True, False, False, False,  True, False],
       [ True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True, False,  True,  True, False],
       [ True,  True,  True, False,  True,  True,  True],
       [ True,  True, False, False,  True, False,  True],
       [ True,  True,  True, False,  True, False, False],
       [False,  True,  True, False,  True, False, False],
       [ True, False,  True,  True, False,  True,  True],
       [ True, False,  True, False,  True, False, False]])

In [26]:
# Now, pass that variable in the brackets to get all elements in our original array that meet that prior criteria

array([9, 9, 9, 8, 6, 7, 6, 9, 9, 9, 7, 7, 7, 9, 7, 8, 6, 7, 8, 8, 8, 6,
       9, 9, 8, 9, 7, 6, 9, 8, 6, 9, 6, 7, 6, 7, 9, 6, 7, 6, 9, 9, 8])

# Part 5 - Concatenation
We're going to concatenate our original two arrays two different ways.  This is useful for merging data sets.  There are 3 ways of doing it, and are covered in the spring homework.
https://github.com/TheDarkTrumpet/BAIS-6040-0EXP-spr2021/blob/master/homework/Homework4.ipynb

In [27]:
# Using one of the options, stack your first array on top of the other. Also output the shape of this as well.


array([[  9,   9,   3,   3,   9,   8,   6],
       [  5,   7,   5,   3,   3,   6,   5],
       [  9,   9,   9,   7,   7,   7,   3],
       [  9,   7,   8,   4,   6,   7,   5],
       [  8,   8,   8,   5,   6,   9,   9],
       [  8,   9,   3,   5,   7,   4,   6],
       [  9,   8,   6,   4,   9,   5,   3],
       [  5,   6,   7,   5,   6,   3,   5],
       [  7,   3,   9,   6,   3,   7,   6],
       [  9,   5,   9,   5,   8,   4,   4],
       [126, 115, 113, 124, 123, 129, 123],
       [122, 127, 129, 129, 133, 126, 117],
       [122, 132, 110, 122, 133, 127, 112],
       [115, 112, 111, 116, 122, 112, 125],
       [111, 111, 124, 114, 125, 120, 115],
       [122, 129, 123, 115, 124, 133, 128],
       [121, 132, 112, 111, 119, 131, 122],
       [119, 128, 121, 131, 129, 124, 127],
       [123, 112, 134, 131, 110, 122, 122],
       [132, 131, 123, 133, 129, 115, 111]])

(20, 7)

In [29]:
# Using one of the options, put them side by side (as if two sheets of paper next to each other).  Output the shape too.

array([[  9,   9,   3,   3,   9,   8,   6, 126, 115, 113, 124, 123, 129,
        123],
       [  5,   7,   5,   3,   3,   6,   5, 122, 127, 129, 129, 133, 126,
        117],
       [  9,   9,   9,   7,   7,   7,   3, 122, 132, 110, 122, 133, 127,
        112],
       [  9,   7,   8,   4,   6,   7,   5, 115, 112, 111, 116, 122, 112,
        125],
       [  8,   8,   8,   5,   6,   9,   9, 111, 111, 124, 114, 125, 120,
        115],
       [  8,   9,   3,   5,   7,   4,   6, 122, 129, 123, 115, 124, 133,
        128],
       [  9,   8,   6,   4,   9,   5,   3, 121, 132, 112, 111, 119, 131,
        122],
       [  5,   6,   7,   5,   6,   3,   5, 119, 128, 121, 131, 129, 124,
        127],
       [  7,   3,   9,   6,   3,   7,   6, 123, 112, 134, 131, 110, 122,
        122],
       [  9,   5,   9,   5,   8,   4,   4, 132, 131, 123, 133, 129, 115,
        111]])

(10, 14)