In [1]:
import numpy as np
np.random.seed(1024)

In [2]:
randomInt = np.random.randint(0, 100, (1, 4))
randomInt

array([[59, 17, 97, 89]])

In [3]:
trueFalses = [[True, False, True, False]]
npTrueFalses = np.asanyarray(trueFalses)
npTrueFalses

array([[ True, False,  True, False]])

In [4]:
randomInt[npTrueFalses]

array([59, 97])