# Midterm

## Purpose

This midterm attempts to touch on a little bit of everything we covered in this course up to this point.  We won't be including Pandas in this midterm, and required knowledge is up through and including NumPy.

There will be 5 main sections of this.  We'll go over types into lists, then sets, then into dictionaries functions, then NumPy.

Some sections tie to other sections, so it's recommended you work on this top down.  I do recommend reading through everything, studying the output, and come up with a "game plan" before you get started.  Try to avoid the urge of starting to code right away, and give yourself plenty of time to figure out the strategy.  The actual coding of this shouldn't take too long.

Readability will count.  Remember that too much in one cell can cause readability issues and can cause difficulty in tracing code.  Like statements in one cell is fine, just avoid putting too much.

In [1]:
import random as rnd
import numpy as np
import inspect

rnd.seed(78223)
np.random.seed(83433)

In [2]:
# Helper functions go in a block near the top, if you decide to make any
# Do NOT put the function generation in Part 4 into this block

# Part 1 - Types

In this section, please create 4 different lists, each with 10 elements.  Below are the types, and formats/ranges

| Type  | Length | Range/Format |
|-------|--------|--------------|
| integer | 10 elements | 3-12  |
| float   | 10 elements | 0-1.0 (0.01, 0.02, 0.1,...0.55,..., 1.0) |
| Boolean | 10 elements | True/False  |
| String  | 10 elements | format: "number (X)", 1 < X < 10, keep the parentheses |

You can use For, While, or List Comprehension.  Do not use sample.

Print the name of the variable, the type of the collection, and the elements contained - for each of the 4 variables we created above.

In [3]:
agesOfCats = [rnd.randint(3, 12) for _ in range(10)]
print(f"agesOfCats is of type: {type(agesOfCats)}, and elements are: {agesOfCats}")

agesOfCats is of type: <class 'list'>, and elements are: [12, 6, 11, 12, 8, 6, 4, 11, 3, 3]


In [4]:
centsOfEnergy = [rnd.randint(0, 100)/100 for _ in range(10)]
print(f"centsOfEnergy is of type: {type(centsOfEnergy)}, and elements are: {centsOfEnergy}")

centsOfEnergy is of type: <class 'list'>, and elements are: [0.7, 0.37, 0.23, 0.41, 0.51, 0.25, 0.29, 0.42, 0.36, 1.0]


In [5]:
exercisedToday = [bool(rnd.randint(0, 1)) for _ in range(10)]
print(f"exercisedToday is of type: {type(exercisedToday)}, and elements are: {exercisedToday}")

exercisedToday is of type: <class 'list'>, and elements are: [False, False, True, False, False, False, True, False, False, True]


In [6]:
housesOnBlock = [f"number ({x})" for x in range(1, 11)]
print(f"housesOnBlock is of type: {type(housesOnBlock)}, and elements are: {housesOnBlock}")

housesOnBlock is of type: <class 'list'>, and elements are: ['number (1)', 'number (2)', 'number (3)', 'number (4)', 'number (5)', 'number (6)', 'number (7)', 'number (8)', 'number (9)', 'number (10)']


# Part 2 - Sets

In this section, please take the variables from part 1, and convert them to sets.  For each one, print out the variable, the type of collection, and the elements contained.

In [7]:
uniqueAgesOfCats = set(agesOfCats)
print(f"uniqueAgesOfCats is of type: {type(uniqueAgesOfCats)}, and elements are: {uniqueAgesOfCats}")

uniqueAgesOfCats is of type: <class 'set'>, and elements are: {3, 4, 6, 8, 11, 12}


In [8]:
uniqueCentsOfEnergy = set(centsOfEnergy)
print(f"uniqueCentsOfEnergy is of type: {type(uniqueCentsOfEnergy)}, and elements are: {uniqueCentsOfEnergy}")

uniqueCentsOfEnergy is of type: <class 'set'>, and elements are: {0.7, 0.37, 0.51, 0.23, 0.41, 0.25, 0.29, 0.42, 0.36, 1.0}


In [9]:
availableExercisedStates = set(exercisedToday)
print(f"availableExercisedStates is of type: {type(availableExercisedStates)}, and elements are: {availableExercisedStates}")

availableExercisedStates is of type: <class 'set'>, and elements are: {False, True}


In [10]:
uniqueHousesOnBlock = set(housesOnBlock)
print(f"uniqueHousesOnBlock is of type: {type(uniqueHousesOnBlock)}, and elements are: {uniqueHousesOnBlock}")

uniqueHousesOnBlock is of type: <class 'set'>, and elements are: {'number (9)', 'number (3)', 'number (4)', 'number (6)', 'number (1)', 'number (5)', 'number (7)', 'number (8)', 'number (10)', 'number (2)'}


# Part 3 - Dictionaries

In this section, please create a dictionary that has 4 keys.  One key for each of the variables in part 2.  The values should be the corresponding values of those variables in part 2.

After that, please create a loop that will iterate over the dictionary and prints the key, then the value elements.  There are many ways to approach this problem.  Please read through the following site (since we haven't covered iteration over a dictionary), and evaluate for yourself which makes the most sense to you and implementat that one.

https://realpython.com/iterate-through-dictionary-python/

After the implementation, please create a markdown cell and explain your choice.

In [11]:
exerciseCatsAndHouses = {
    "uniqueAgesOfCats": uniqueAgesOfCats,
    "uniqueCentsOfEnergy": uniqueCentsOfEnergy,
    "availableExercisedStates": availableExercisedStates,
    "uniqueHousesOnBlock": uniqueHousesOnBlock
}
exerciseCatsAndHouses

{'uniqueAgesOfCats': {3, 4, 6, 8, 11, 12},
 'uniqueCentsOfEnergy': {0.23,
  0.25,
  0.29,
  0.36,
  0.37,
  0.41,
  0.42,
  0.51,
  0.7,
  1.0},
 'availableExercisedStates': {False, True},
 'uniqueHousesOnBlock': {'number (1)',
  'number (10)',
  'number (2)',
  'number (3)',
  'number (4)',
  'number (5)',
  'number (6)',
  'number (7)',
  'number (8)',
  'number (9)'}}

In [12]:
for key, values in exerciseCatsAndHouses.items():
    print(f"Key: {key}, Values: {values}")

Key: uniqueAgesOfCats, Values: {3, 4, 6, 8, 11, 12}
Key: uniqueCentsOfEnergy, Values: {0.7, 0.37, 0.51, 0.23, 0.41, 0.25, 0.29, 0.42, 0.36, 1.0}
Key: availableExercisedStates, Values: {False, True}
Key: uniqueHousesOnBlock, Values: {'number (9)', 'number (3)', 'number (4)', 'number (6)', 'number (1)', 'number (5)', 'number (7)', 'number (8)', 'number (10)', 'number (2)'}


# Part 4 - Functions

In the previous sections, part 1-3, we have a lot of duplicated code.  In this section, we'll resolve one of those issues - and that being the print and format of the statement.

In this section, please write a function that takes a collection (List, Set, Tuple, Dictionary), and prints out the following information about it:

* Object Type - List, Set, Tuple, etc.
* Up to 5 elements of the collection.
* The length of the collection

This is a bit more tricky than it'll appear at first.  But, I caution you not to overthink this problem too much.  So you don't need to use "enumerate" (which would allow us to iterate over a set.  Think simply about it.  A list can be iterated, what can we do about a set?  Dictionary is another special case, but conceptually that was done in part 3.  So what's left is the ability to check the types and deal with them appropriately.

One hint I will give, outside that, is you only need an if statement with two parts (if, else).

Another hint I'll give is that your function may end up fairly large if not careful.  You can break up a function into multiple functions, and have that main function call the other functions, if desired.  Consider the readability in all this.

Test your function with a few types to prove it works.

In [13]:
def printDictionary(dictionary):
    """Given a dictionary as input, print out the key, and up to 5 values"""
    print(f"Type: {type(dictionary)}")
    for key, values in dictionary.items():
        print(f"Key: {key}")
        printGeneral(values)

def printGeneral(collection):
    """Given a non-dictionary type, print out the type, and up to 5 values"""
    castedCollection = list(collection)[0:5]
    print(f"Type: {type(collection)}")
    print(f"{len(castedCollection)} elements (of {len(collection)}): {list(castedCollection)}")

def printCollection(collection):
    """Generalized print function, main entry point. Accepts all collection types"""
    if type(collection) is dict:
        printDictionary(collection)
    else:
        printGeneral(collection)

In [14]:
printCollection(exerciseCatsAndHouses)

Type: <class 'dict'>
Key: uniqueAgesOfCats
Type: <class 'set'>
5 elements (of 6): [3, 4, 6, 8, 11]
Key: uniqueCentsOfEnergy
Type: <class 'set'>
5 elements (of 10): [0.7, 0.37, 0.51, 0.23, 0.41]
Key: availableExercisedStates
Type: <class 'set'>
2 elements (of 2): [False, True]
Key: uniqueHousesOnBlock
Type: <class 'set'>
5 elements (of 10): ['number (9)', 'number (3)', 'number (4)', 'number (6)', 'number (1)']


In [15]:
printCollection(agesOfCats)

Type: <class 'list'>
5 elements (of 10): [12, 6, 11, 12, 8]


In [16]:
printCollection(uniqueAgesOfCats)

Type: <class 'set'>
5 elements (of 6): [3, 4, 6, 8, 11]


# Part 5 - NumPy

The NumPy section will have a few subparts to the problem.  They'll rely on working code from the previous 4 parts, especially the first part.

## Part 5a - Create a matrix

This part of the exam is probably the most complicated to both explain, and to process.  We'll rely on two prior structures (the randomList and randomFloats) of the list to generate a 10x10 matrix using what we got from the creation of those two lists in a rule based format.

Steps:
1.  Get the mean of your random list that was created in part 1.
2.  Write a loop that'll create a list (or lists in a list), depending on how you go about converting into a NumPy array in 5b that follows the following logic:

ri = random integers

rb = random bool

| Condition (ri)  | Condition (rb) | Random Range |
|-----------------|----------------|--------------|
| >= mean         | True           | 100 to 200   |
| >= mean         | False          | -200 to -100 |
| < mean          | True           | 1 - 100      |
| < mean          | False          | -100 to -1   |

Some Tips/Notes:
* Pay attention to the output.  Since we're looping the same rules for each row, the range/rules should be the **same** for the entire column.  Meaning, if we have the random [-200 to -100], we should see the entire column be in that range, for all rows.
* It may help to start this with printing out (or debugging if using PyCharm) to get an idea of what the values are for that iteration, and the rule that's hit.

In [17]:
# Print the random integer list, so we can match things up easier visually
agesOfCats

[12, 6, 11, 12, 8, 6, 4, 11, 3, 3]

In [18]:
# Print the random Boolean list, so we can match things up easier visually
exercisedToday

[False, False, True, False, False, False, True, False, False, True]

In [19]:
meanAgesOfCats = sum(agesOfCats) / len(agesOfCats)
print(f"meanAgesOfCats mean is {meanAgesOfCats}")

meanAgesOfCats mean is 7.6


In [20]:
numberOfCatsInStudy = 10     # Define the number of cats we should generate data for
print(f"Generating {numberOfCatsInStudy} samples")

Generating 10 samples


In [21]:
catsAndExerciseEfficiency = []
while numberOfCatsInStudy > 0:
    temporarySample = []
    x = 0
    # One option, using zip, not covered, but for exposing it as an option
    # for currentCatAge, exerciseToday in zip(agesOfCats, exercisedToday):
    while x < len(agesOfCats):
        currentCatAge = agesOfCats[x]
        exerciseToday = exercisedToday[x]
        if currentCatAge >= meanAgesOfCats and exerciseToday:
            temporarySample.append(rnd.randint(100, 200))
        elif currentCatAge >= meanAgesOfCats and not exerciseToday:
            temporarySample.append(-rnd.randint(100, 200))
        elif currentCatAge < meanAgesOfCats and exerciseToday:
            temporarySample.append(rnd.randint(1, 100))
        elif currentCatAge < meanAgesOfCats and not exerciseToday:   # Could use else here too
            temporarySample.append(-rnd.randint(1, 100))
        x += 1
    catsAndExerciseEfficiency.append(temporarySample)
    numberOfCatsInStudy -= 1
catsAndExerciseEfficiency

[[-138, -18, 152, -104, -137, -40, 15, -193, -98, 13],
 [-109, -63, 193, -136, -112, -94, 98, -109, -79, 90],
 [-190, -27, 199, -129, -110, -38, 5, -100, -12, 49],
 [-128, -31, 192, -192, -169, -66, 66, -108, -50, 54],
 [-133, -77, 147, -111, -120, -19, 7, -181, -24, 32],
 [-178, -22, 122, -155, -114, -8, 99, -116, -98, 66],
 [-184, -56, 130, -132, -170, -97, 14, -188, -12, 34],
 [-164, -41, 161, -140, -115, -44, 69, -140, -64, 10],
 [-101, -14, 150, -173, -115, -31, 5, -135, -5, 64],
 [-108, -21, 104, -169, -133, -65, 91, -110, -61, 44]]

## Part 5b - convert into NumPy Matrix

As long as you got the above right (and there's a few ways you can do the above), this should be one line.  Please convert your list structure above into a NumPy array, and print out what that looks like.

In [22]:
npCatsAndExerciseEfficiency = np.asarray(catsAndExerciseEfficiency)
npCatsAndExerciseEfficiency

array([[-138,  -18,  152, -104, -137,  -40,   15, -193,  -98,   13],
       [-109,  -63,  193, -136, -112,  -94,   98, -109,  -79,   90],
       [-190,  -27,  199, -129, -110,  -38,    5, -100,  -12,   49],
       [-128,  -31,  192, -192, -169,  -66,   66, -108,  -50,   54],
       [-133,  -77,  147, -111, -120,  -19,    7, -181,  -24,   32],
       [-178,  -22,  122, -155, -114,   -8,   99, -116,  -98,   66],
       [-184,  -56,  130, -132, -170,  -97,   14, -188,  -12,   34],
       [-164,  -41,  161, -140, -115,  -44,   69, -140,  -64,   10],
       [-101,  -14,  150, -173, -115,  -31,    5, -135,   -5,   64],
       [-108,  -21,  104, -169, -133,  -65,   91, -110,  -61,   44]])

## Part 5c - numpy.reshape

We will practice reading documentation, and expanding our knowledge of NumPy.

Please reference the following document:
https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

Please take the array you created in 5b, and use numpy reshape on it to convert it into a 20x5 array.  Do not save the result or overwrite your variable from 5b, but do show the output of what the reshape would do.

In [23]:
np.reshape(npCatsAndExerciseEfficiency, (20, 5))

array([[-138,  -18,  152, -104, -137],
       [ -40,   15, -193,  -98,   13],
       [-109,  -63,  193, -136, -112],
       [ -94,   98, -109,  -79,   90],
       [-190,  -27,  199, -129, -110],
       [ -38,    5, -100,  -12,   49],
       [-128,  -31,  192, -192, -169],
       [ -66,   66, -108,  -50,   54],
       [-133,  -77,  147, -111, -120],
       [ -19,    7, -181,  -24,   32],
       [-178,  -22,  122, -155, -114],
       [  -8,   99, -116,  -98,   66],
       [-184,  -56,  130, -132, -170],
       [ -97,   14, -188,  -12,   34],
       [-164,  -41,  161, -140, -115],
       [ -44,   69, -140,  -64,   10],
       [-101,  -14,  150, -173, -115],
       [ -31,    5, -135,   -5,   64],
       [-108,  -21,  104, -169, -133],
       [ -65,   91, -110,  -61,   44]])

## Part 5d - numpy.extract

The homework we did for Homework 4 worked at conditionally extracting elements.  This is another way we can accomplish the same generalized goal.

Please read the following documentation:
https://numpy.org/doc/stable/reference/generated/numpy.extract.html

In this exercise, please pull out all elements that have negative values, between -40 and -70.

Tips:
* Remember what you did on Homework 4

In [24]:
poorExerciseScoreMatch = np.vectorize(lambda x: -70 <= x <= -40)
poorExerciseScoreMatches = poorExerciseScoreMatch(npCatsAndExerciseEfficiency)
poorExerciseScoreMatches

array([[False, False, False, False, False,  True, False, False, False,
        False],
       [False,  True, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True, False, False,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True, False, False, False, False, False, False, False,
        False],
       [False,  True, False, False, False,  True, False, False,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True, False, False,  True,
        False]])

In [25]:
np.extract(poorExerciseScoreMatches, npCatsAndExerciseEfficiency)

array([-40, -63, -66, -50, -56, -41, -44, -64, -65, -61])