In [1]:
import numpy as np
import numpy.random as rnd

In [2]:
rnd.seed(237482374)

# Demonstrating the concept of vectorize
Why use lambdas over named functions?  Doesn't clutter global namespace

In [3]:
myMatrix = rnd.randint(1, 100, (10, 5))
myMatrix

array([[ 5,  7,  1, 60, 58],
       [23, 46, 70, 65, 70],
       [77, 39, 53, 29, 35],
       [32, 29, 38, 38, 87],
       [94, 27,  8, 15, 57],
       [14, 49, 79, 71, 25],
       [60, 98, 70, 54, 75],
       [60, 91,  1, 20, 45],
       [43, 87, 79, 27, 42],
       [78, 91, 74, 46, 62]])

In [4]:
myMatrix * myMatrix

array([[  25,   49,    1, 3600, 3364],
       [ 529, 2116, 4900, 4225, 4900],
       [5929, 1521, 2809,  841, 1225],
       [1024,  841, 1444, 1444, 7569],
       [8836,  729,   64,  225, 3249],
       [ 196, 2401, 6241, 5041,  625],
       [3600, 9604, 4900, 2916, 5625],
       [3600, 8281,    1,  400, 2025],
       [1849, 7569, 6241,  729, 1764],
       [6084, 8281, 5476, 2116, 3844]])

In [5]:
addOneToEachElement = np.vectorize(lambda x: x + 1)

In [6]:
def addOne(x):
    return x + 1

In [7]:
addOneToEachElement2 = np.vectorize(addOne)

In [8]:
myMatrix

array([[ 5,  7,  1, 60, 58],
       [23, 46, 70, 65, 70],
       [77, 39, 53, 29, 35],
       [32, 29, 38, 38, 87],
       [94, 27,  8, 15, 57],
       [14, 49, 79, 71, 25],
       [60, 98, 70, 54, 75],
       [60, 91,  1, 20, 45],
       [43, 87, 79, 27, 42],
       [78, 91, 74, 46, 62]])

In [9]:
myMatrixPlusOne = addOneToEachElement(myMatrix)
myMatrixPlusOne

array([[ 6,  8,  2, 61, 59],
       [24, 47, 71, 66, 71],
       [78, 40, 54, 30, 36],
       [33, 30, 39, 39, 88],
       [95, 28,  9, 16, 58],
       [15, 50, 80, 72, 26],
       [61, 99, 71, 55, 76],
       [61, 92,  2, 21, 46],
       [44, 88, 80, 28, 43],
       [79, 92, 75, 47, 63]])

In [10]:
addOneToEachElement2(myMatrix)

array([[ 6,  8,  2, 61, 59],
       [24, 47, 71, 66, 71],
       [78, 40, 54, 30, 36],
       [33, 30, 39, 39, 88],
       [95, 28,  9, 16, 58],
       [15, 50, 80, 72, 26],
       [61, 99, 71, 55, 76],
       [61, 92,  2, 21, 46],
       [44, 88, 80, 28, 43],
       [79, 92, 75, 47, 63]])

In [11]:
complicatedLookup = {
    "1": "Cat",
    "2": "Dog",
    "3": "Snake"
}
quickLookup = np.vectorize(lambda x: complicatedLookup[str(x)])
myAnimalMatrix = rnd.randint(1, 4, (10, 5))
myAnimalMatrix

array([[1, 3, 2, 1, 2],
       [1, 3, 3, 3, 3],
       [1, 2, 2, 2, 1],
       [1, 1, 1, 3, 1],
       [1, 1, 3, 2, 2],
       [1, 1, 3, 3, 2],
       [3, 2, 3, 2, 1],
       [3, 3, 2, 1, 2],
       [3, 3, 2, 1, 1],
       [1, 2, 3, 3, 2]])

In [12]:
quickLookup(myAnimalMatrix)

array([['Cat', 'Snake', 'Dog', 'Cat', 'Dog'],
       ['Cat', 'Snake', 'Snake', 'Snake', 'Snake'],
       ['Cat', 'Dog', 'Dog', 'Dog', 'Cat'],
       ['Cat', 'Cat', 'Cat', 'Snake', 'Cat'],
       ['Cat', 'Cat', 'Snake', 'Dog', 'Dog'],
       ['Cat', 'Cat', 'Snake', 'Snake', 'Dog'],
       ['Snake', 'Dog', 'Snake', 'Dog', 'Cat'],
       ['Snake', 'Snake', 'Dog', 'Cat', 'Dog'],
       ['Snake', 'Snake', 'Dog', 'Cat', 'Cat'],
       ['Cat', 'Dog', 'Snake', 'Snake', 'Dog']], dtype='<U5')

In [13]:
addOne = 1

# Random Seeds

Seed should be done once per execution (once in a file), because it resets the starting spot each and every time.

In [14]:
import random as rndnew
rndnew.seed(1)

In [15]:
rndnew.randint(1, 100)

18

In [16]:
def myFunction():
    rndnew.seed(1)
    return [rndnew.randint(1, 10) for _ in range(20)]

In [17]:
myFunction()

[3, 10, 2, 5, 2, 8, 8, 8, 7, 4, 2, 8, 1, 7, 7, 10, 1, 8, 5, 4]

In [18]:
myFunction()

[3, 10, 2, 5, 2, 8, 8, 8, 7, 4, 2, 8, 1, 7, 7, 10, 1, 8, 5, 4]

In [19]:
for _ in range(5):
    rndnew.seed(1)
    print(f"Picking new random number {rndnew.randint(1, 10)}")

Picking new random number 3
Picking new random number 3
Picking new random number 3
Picking new random number 3
Picking new random number 3


# Slicing Matrices

In [20]:
mySliceMatrix = rnd.randint(1, 100, (10, 10))
mySliceMatrix

array([[76,  6, 13, 59,  7,  6, 95, 43, 74, 78],
       [24, 49, 61, 72, 65, 13, 43, 90, 62, 35],
       [41, 97, 12,  3, 73, 88, 12, 94, 26, 49],
       [41, 53, 42,  6, 11, 62,  2, 52, 61, 96],
       [91, 89, 24, 59,  7, 42, 55, 51, 85, 27],
       [80, 83, 78, 17, 16, 69, 11, 95, 93, 12],
       [61, 56, 30, 13, 70, 38,  6, 50,  4, 33],
       [51, 47, 13, 55, 65, 82, 32, 55, 44, 75],
       [65, 14, 45, 88, 15, 53, 29, 17, 66, 27],
       [32, 52, 49, 82, 72, 33, 50, 63, 98, 55]])

In [21]:
# Getting 4,4
mySliceMatrix[3,3]

6

In [22]:
# Getting -3,-3
mySliceMatrix[-3,-3]

55

In [23]:
# Getting -3, -4
mySliceMatrix[-3, -4]

32

In [24]:
# Getting first row
mySliceMatrix[0]

array([76,  6, 13, 59,  7,  6, 95, 43, 74, 78])

In [25]:
# Getting the last row
mySliceMatrix[-1]

array([32, 52, 49, 82, 72, 33, 50, 63, 98, 55])

In [26]:
# Specific row and a few elements in a column
y = mySliceMatrix[6, 2:5]
y

array([30, 13, 70])

In [27]:
# .ix_ Notation, of the above
x = mySliceMatrix[np.ix_([6],range(2, 5))]
x

array([[30, 13, 70]])

In [28]:
# .ix_ pick first and last of top, first and last of bottom
mySliceMatrix[np.ix_([0, -1], [0, -1])]

array([[76, 78],
       [32, 55]])

In [29]:
# (0, 0), (0, 1), (2, 0), (2, 1), ... (4, 1)
mySliceMatrix[np.ix_([0, 2, 4], [0, 1])]

array([[76,  6],
       [41, 97],
       [91, 89]])

In [30]:
# Why not ranges?
mySliceMatrix[[0, 2, 4], 0:2]

array([[76,  6],
       [41, 97],
       [91, 89]])

In [31]:
# This will throw an error message
# mySliceMatrix[[0, 2, 4], [0, 5]]

In [32]:
mySliceMatrix[np.ix_([0, 2, 4], [0, 5])]

array([[76,  6],
       [41, 88],
       [91, 42]])

In [33]:
# You can do ranges like the below
mySliceMatrix[np.ix_([x for x in range(len(mySliceMatrix))], [0, 5])]

array([[76,  6],
       [24, 13],
       [41, 88],
       [41, 62],
       [91, 42],
       [80, 69],
       [61, 38],
       [51, 82],
       [65, 53],
       [32, 33]])

In [34]:
np.shape(y)

(3,)

In [35]:
np.shape(x)

(1, 3)

In [36]:
def getSlice(matrix, y1, x1, x2):
    return matrix[y1, x1:x2]

In [37]:
getSlice(mySliceMatrix, 6, 2, 5)

array([30, 13, 70])

In [38]:
# Do not do the following (usually used in demonstrations, but don't do it!)
def getSlice2(y1, x1, x2):
    return mySliceMatrix[y1, x1:x2]

In [39]:
getSlice2(6, 2, 5)

array([30, 13, 70])

# Lengths of matrices

In [40]:
myMatrix

array([[ 5,  7,  1, 60, 58],
       [23, 46, 70, 65, 70],
       [77, 39, 53, 29, 35],
       [32, 29, 38, 38, 87],
       [94, 27,  8, 15, 57],
       [14, 49, 79, 71, 25],
       [60, 98, 70, 54, 75],
       [60, 91,  1, 20, 45],
       [43, 87, 79, 27, 42],
       [78, 91, 74, 46, 62]])

In [41]:
len(myMatrix)

10

In [42]:
len(myMatrix[0])

5

In [43]:
# myMatrix = rnd.randint(5, 100, (200, 200))

In [44]:
# Don't do the below, because things are hardcoded, and you'll likely
# cause problems when modifying something like the above
y = 0
while y < 10:
    x = 0
    while x < 5:
        print(f"Element: {myMatrix[y,x]}")
        x += 1
    y += 1

Element: 5
Element: 7
Element: 1
Element: 60
Element: 58
Element: 23
Element: 46
Element: 70
Element: 65
Element: 70
Element: 77
Element: 39
Element: 53
Element: 29
Element: 35
Element: 32
Element: 29
Element: 38
Element: 38
Element: 87
Element: 94
Element: 27
Element: 8
Element: 15
Element: 57
Element: 14
Element: 49
Element: 79
Element: 71
Element: 25
Element: 60
Element: 98
Element: 70
Element: 54
Element: 75
Element: 60
Element: 91
Element: 1
Element: 20
Element: 45
Element: 43
Element: 87
Element: 79
Element: 27
Element: 42
Element: 78
Element: 91
Element: 74
Element: 46
Element: 62


In [45]:
# Dynamic programming (looking at the contents/lengths of previously defined variables)
# helps to avoid issues with hardcoded values
y = 0
while y < len(myMatrix):
    x = 0
    while x < len(myMatrix[0]):
        print(f"Element: {myMatrix[y,x]}")
        x += 1
    y += 1

Element: 5
Element: 7
Element: 1
Element: 60
Element: 58
Element: 23
Element: 46
Element: 70
Element: 65
Element: 70
Element: 77
Element: 39
Element: 53
Element: 29
Element: 35
Element: 32
Element: 29
Element: 38
Element: 38
Element: 87
Element: 94
Element: 27
Element: 8
Element: 15
Element: 57
Element: 14
Element: 49
Element: 79
Element: 71
Element: 25
Element: 60
Element: 98
Element: 70
Element: 54
Element: 75
Element: 60
Element: 91
Element: 1
Element: 20
Element: 45
Element: 43
Element: 87
Element: 79
Element: 27
Element: 42
Element: 78
Element: 91
Element: 74
Element: 46
Element: 62


# Loops
## When to use cell

* For Loops - Loops over a collection (list, tuple) [Avoid use with dictionary or set unless needed and you know what you're doing]
* While Loops - Loops while a condition is true (breaks when false)
* Map/Filter/List Comprehension - Short versions/shortcuts for a For loop.

In [46]:
# For loops
for x in range(10):
    pass  # Means skip doing anything, allows one to compile, and is useful first step
for x in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]:
    pass # Same as above.
for x in (0, 1, 2, 3, 4, 5, 6, 7, 8, 9):
    pass # Same as above.
# map(lambda x: pass for x in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
  # The above is the same as the other for loops, just not syntax-correct

for x in {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}:
    pass # do NOT do the above!.

In [47]:
# While loops
sdlfjsdllkjsldkjflsjdfsdf = 0
while sdlfjsdllkjsldkjflsjdfsdf < 10:
    sdlfjsdllkjsldkjflsjdfsdf = sdlfjsdllkjsldkjflsjdfsdf + 1
    # sdlfjsdllkjsldkjflsjdfsdf += 1  <--- Same as above!

In [48]:
sdlfjsdllkjsldkjflsjdfsdf = 0
while True:
    if sdlfjsdllkjsldkjflsjdfsdf > 10:
        break
    sdlfjsdllkjsldkjflsjdfsdf += 1