# 2021-06-21.supplemental

# True/False and Numpy

In [4]:
import numpy as np

aList = [5, 7, 2]
print(f"aList => {type(aList)} contents: {aList}")

aList => <class 'list'> contents: [5, 7, 2]


In [5]:
aNumPyArray = np.asarray(aList)
print(f"aList => {type(aNumPyArray)} contents: {aNumPyArray}")

aList => <class 'numpy.ndarray'> contents: [5 7 2]


In [6]:
aMultiDimensionalList = [[1, 2, 3], [4, 5, 6]]
print(f"aList => {type(aMultiDimensionalList)} contents: {aMultiDimensionalList}")

aList => <class 'list'> contents: [[1, 2, 3], [4, 5, 6]]


In [8]:
aMultiDimensionalArray = np.asarray(aMultiDimensionalList)
print(f"aList => {type(aMultiDimensionalArray)} contents: {aMultiDimensionalArray}")
aMultiDimensionalArray

aList => <class 'numpy.ndarray'> contents: [[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
list(filter(lambda x: x, aList))   # Returns Everything
list(filter(lambda x: x>5, aList)) # Returns just 7

[7]

In [12]:
aTruthList = [True, False, True]
aNumPyArray[aTruthList]

array([5, 2])

In [22]:
# If you use the below, it's a list with 1 element (represented as 2 dimension
aMultiDimensionalTruth = [[[True,True,True],[True,True,True]]]
aMultiDimensionalArray[aMultiDimensionalTruth]

<ipython-input-22-d44bec444b07>:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  aMultiDimensionalArray[aMultiDimensionalTruth]


array([1, 2, 3, 4, 6])

In [21]:
# Alternative way to the above
aMultiDimensionalTruth = [[True,True,True],[True,True,True]]
aMultiDimensionalTruthArray = np.asarray(aMultiDimensionalTruth)
aMultiDimensionalArray[aMultiDimensionalTruthArray]

array([1, 2, 3, 4, 5, 6])

# Documentation

Be comfortable reading documentation, what's required and not.

# Nested Loops

In [25]:
for x in range(5):
    for y in range(5, 10):
        print(f"x => {x}, y => {y}")

x => 0, y => 5
x => 0, y => 6
x => 0, y => 7
x => 0, y => 8
x => 0, y => 9
x => 1, y => 5
x => 1, y => 6
x => 1, y => 7
x => 1, y => 8
x => 1, y => 9
x => 2, y => 5
x => 2, y => 6
x => 2, y => 7
x => 2, y => 8
x => 2, y => 9
x => 3, y => 5
x => 3, y => 6
x => 3, y => 7
x => 3, y => 8
x => 3, y => 9
x => 4, y => 5
x => 4, y => 6
x => 4, y => 7
x => 4, y => 8
x => 4, y => 9


In [26]:
x = 0
while x < 5:
    y = 5
    while y < 10:
        print(f"x => {x}, y => {y}")
        y += 1
    x += 1

x => 0, y => 5
x => 0, y => 6
x => 0, y => 7
x => 0, y => 8
x => 0, y => 9
x => 1, y => 5
x => 1, y => 6
x => 1, y => 7
x => 1, y => 8
x => 1, y => 9
x => 2, y => 5
x => 2, y => 6
x => 2, y => 7
x => 2, y => 8
x => 2, y => 9
x => 3, y => 5
x => 3, y => 6
x => 3, y => 7
x => 3, y => 8
x => 3, y => 9
x => 4, y => 5
x => 4, y => 6
x => 4, y => 7
x => 4, y => 8
x => 4, y => 9


In [27]:
def aFunction():
    print("here")

x = 0
while x < 5:
    aFunction()
    x += 1

here
here
here
here
here


In [28]:
aMultiDimensionalArray

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
x = y = 0
while x < 3:
    y = 0
    while y < 2:
        print(f"{aMultiDimensionalArray[y,x]}")
        y += 1
    x += 1

1
4
2
5
3
6


# Lambdas

In [34]:
def aFunction(x, y, default = 0):
    print(f"Incoming variables: {x}, {y}, {default}")
    return (x + y) * default

In [32]:
aFunction

<function __main__.aFunction(x, y, default=0)>

In [35]:
aFunction(5, 3, 3)

Incoming variables: 5, 3, 3


24

In [36]:
aFunction = lambda x, y, default = 0: (x + y) * default

In [37]:
aFunction(5, 3, 3)


24

In [42]:
aFunctionFiveElements = map(lambda x, y, default = 0: (x + y) * default, [1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [5, 5, 5, 5, 5])
aFunctionFiveElements

In [43]:
list(aFunctionFiveElements)

[35, 45, 55, 65, 75]

In [66]:
aFunctionFiveElements2 = map(aFunction, [1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [5, 5, 5, 5, 5])
aFunctionFiveElements2

In [64]:
#aFunctionFiveElements2

[35, 45, 55, 65, 75]

In [67]:
list(filter(lambda x: x <= 55, aFunctionFiveElements2))

[35, 45, 55]