# MidtermPractice.01.ipynb

# Purpose
This is a set of exercises designed to help test for the **practical** knowledge related to the midterm exam.  The format will be similar between the two.

# Types

Generate a list of 10 random float elements, between 0 and 1 [0, 0.01, 0.02, ..., 0.99, 1] using both a for and while loop (not a comprehension).  The numbers should be a precision of 2.

In [1]:
import random as rnd
rnd.seed(50923)

In [2]:
randomListFor = []
for _ in range(10):
    randomListFor.append(rnd.randint(0, 100)/100.0)
randomListFor

[0.05, 0.66, 0.16, 0.59, 0.8, 0.59, 0.36, 0.68, 0.56, 0.4]

In [3]:
randomListWhile = []
while len(randomListWhile) < 10:
    randomListWhile.append(rnd.randint(0, 100)/100.0)
randomListWhile

[0.96, 0.24, 0.52, 0.68, 0.55, 0.62, 0.87, 0.7, 0.67, 0.99]

# Grouping elements
Write a function that accepts a list.  For very two elements in the list, group them together in a tuple, and return, in the end, a list of tuples.  This function should be durable, not reliant on a specific number of elements, and it should be able to handle both even and odds.  Pay attention to the output of this.

In [4]:
def groupElements(inElements):
    counter = 0
    returnStructure = []
    while counter < len(inElements):
        currentElement = inElements[counter]
        nextElement = None
        if counter + 1 < len(inElements):
            nextElement = inElements[counter+1]
        returnStructure.append((currentElement, nextElement))
        counter += 2
    return returnStructure

In [5]:
groupElements([1, 5, 9])

[(1, 5), (9, None)]

In [6]:
groupElements([5, 8, 9, 2])

[(5, 8), (9, 2)]

# Programmatic Slices

Write a loop that would select greater rages of elements each time.  So the first iteration, we pick 1 element. The second we pick 2, the third we pick 3, and so on til we pick a range that starts to extend the end of the list.  Each iteration print the iteration number, the elements chosen.  Look at the output for more information.  The test data set was provided for you.

In [7]:
sequenceNumbers = [x for x in range(100)]

In [8]:
iterationCounter = 1
currentOffset = 0
while True:
                          # 1st time: sequenceNumbers[0:1]
    slice = sequenceNumbers[currentOffset:currentOffset + iterationCounter]
    print(f"Iteration: {iterationCounter}, elements: {slice}")
    currentOffset += iterationCounter
    iterationCounter += 1
    if currentOffset > len(sequenceNumbers):
        break

Iteration: 1, elements: [0]
Iteration: 2, elements: [1, 2]
Iteration: 3, elements: [3, 4, 5]
Iteration: 4, elements: [6, 7, 8, 9]
Iteration: 5, elements: [10, 11, 12, 13, 14]
Iteration: 6, elements: [15, 16, 17, 18, 19, 20]
Iteration: 7, elements: [21, 22, 23, 24, 25, 26, 27]
Iteration: 8, elements: [28, 29, 30, 31, 32, 33, 34, 35]
Iteration: 9, elements: [36, 37, 38, 39, 40, 41, 42, 43, 44]
Iteration: 10, elements: [45, 46, 47, 48, 49, 50, 51, 52, 53, 54]
Iteration: 11, elements: [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]
Iteration: 12, elements: [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77]
Iteration: 13, elements: [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]
Iteration: 14, elements: [91, 92, 93, 94, 95, 96, 97, 98, 99]


# NumPy
We'll generate a 6x6 matrix.  In this process, go down the diagonal of the matrix and collect the elements, 2 by 2.  So we'll grab the 5, 2, 6, 3 from the matrix during the first iteration.  IN the end you should have a list to 3 matrix collections.  We'll end print these out, then print out he summed matrix for each one (so a list of 3 summed matrices), then the sum of that.

In [9]:
import numpy.random as nprand
nprand.seed(6088)

In [10]:
randomMatrix = nprand.randint(1, 10, (6, 6))
randomMatrix

array([[5, 2, 6, 3, 4, 1],
       [6, 3, 9, 6, 1, 6],
       [8, 7, 6, 1, 3, 3],
       [3, 8, 7, 8, 1, 8],
       [7, 6, 8, 3, 3, 8],
       [2, 6, 3, 5, 4, 3]])

In [11]:
counter = 0
diagonals = []
while counter < len(randomMatrix):
    subMatrix = randomMatrix[counter:counter+2,counter:counter+2]
    diagonals.append(subMatrix)
    counter = counter + 2

In [12]:
print("The diagonals are as follows:")
for diagonal in diagonals:
    print(diagonal)

The diagonals are as follows:
[[5 2]
 [6 3]]
[[6 1]
 [7 8]]
[[3 8]
 [4 3]]


In [13]:
diagonalsSum = list(map(lambda x: x.sum(), diagonals))
print(f"The sums for each diagonal is: {diagonalsSum}")

The sums for each diagonal is: [16, 22, 18]


In [14]:
print(f"The entire sum of this is: {sum(diagonalsSum)}")

The entire sum of this is: 56
