# 04.01.01 - NumPy

## Description

This document goes over the very basics of NumPy, general initialization, accessing and so on

## Requirements
NumPy

In [1]:
import numpy as np

In [2]:
myList = range(1, 10)
mySimpleArray = np.array(myList)
mySimpleArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Initialize with a dtype
myList = range(1, 10)
myFloatArray = np.array(myList, dtype=float)
myFloatArray

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
# Accessing elements
myFloatArray[0]

1.0

In [5]:
# Accessing a range
myFloatArray[-3:]

array([7., 8., 9.])

## Matrices
A matrix is a 2-dimensional array.

In [6]:
myList = range(1, 11)
mySimpleMatrix = np.array(myList)
mySimpleMatrix = np.reshape(mySimpleMatrix, (2, 5))
mySimpleMatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
# Pulling elements out
mySimpleMatrix[0,1]  # Single element, remember 0 starting point

2

In [8]:
mySimpleMatrix[1,1]


7

In [9]:
# Pulling ranges out
mySimpleMatrix[1:]

array([[ 6,  7,  8,  9, 10]])

In [10]:
mySimpleMatrix[1, 3:]

array([ 9, 10])

In [11]:
# Assignment
mySimpleMatrix[1, 1] = 500
mySimpleMatrix

# We can also transpose a matrix, too
mySimpleMatrix.transpose()

array([[  1,   6],
       [  2, 500],
       [  3,   8],
       [  4,   9],
       [  5,  10]])

## Generating data types

We can generate test data easier using numpy in a lot of ways.

In [12]:
randomInts = np.random.randint(1, 100, 10)
randomInts

array([77,  3, 36, 60, 47, 70, 32, 14, 65, 46])

In [13]:
randMatrix = np.random.randint(1, 100, size=(10,10))
randMatrix

array([[45, 86, 93,  1, 44, 42, 65, 60, 67, 42],
       [79, 83, 92, 42,  9, 43, 93, 69, 61, 74],
       [25, 66, 65, 46, 76, 28, 83,  9, 24, 97],
       [61, 90, 13, 79, 42, 81,  9, 75, 56, 14],
       [43, 45, 94, 47, 51, 48, 89, 52,  1,  7],
       [87, 51, 96, 72, 90, 82, 23, 34, 38, 34],
       [64, 71, 32, 33, 70, 44, 99, 66, 25, 61],
       [31, 17, 34, 19,  5, 10, 15, 38, 20,  5],
       [42, 71, 15, 55, 18, 44, 55, 86, 46, 45],
       [94, 39, 33, 25, 58, 77, 55, 97,  8,  2]])

## Adding and processing Arrays/matrices

In [14]:
randMatrixA = np.random.randint(1, 100, size=(10,10))
randMatrixB = np.random.randint(1, 100, size=(10,10))
randMatrixC = randMatrixA + randMatrixB  # Note we're adding the two elements
randMatrixC

array([[ 82,  82,  87,  84, 162, 130,  85,  23, 118,  17],
       [ 99, 103,  69, 112, 134, 131, 111,  34, 132, 114],
       [107, 168, 175, 123,  92,  68,  85,  92, 111, 163],
       [123, 135, 131, 114,  87, 170,  72, 141,  15,  33],
       [ 69,  89, 100,  74,  72, 136, 104, 161,  84,  84],
       [124, 156, 104, 103,  66, 179,  99, 133,  87,  66],
       [166, 114,  95, 123, 175,  77,   3, 118, 116,  30],
       [ 67, 118,  98,  94, 113,  74,  68,  74,  34, 141],
       [172,  96, 111,  80, 134,  48, 121, 169,  97,  55],
       [122,  76,  96,  63,  92, 104, 180,  87, 101, 195]])

In [15]:
randMatrixA

array([[17, 81, 86,  4, 93, 40, 37, 19, 65, 12],
       [64, 21, 26, 55, 54, 76, 14,  9, 36, 90],
       [80, 79, 76, 96, 20, 36, 15, 24, 66, 91],
       [32, 71, 32, 32, 10, 76, 48, 50, 11, 11],
       [55, 28, 91, 54, 40, 48, 89, 90, 46, 35],
       [42, 64, 21, 93, 38, 85, 15, 80, 49, 13],
       [84, 61, 67, 48, 80,  7,  2, 32, 95, 16],
       [65, 19, 92,  8, 23, 27,  7, 52, 22, 81],
       [85, 38, 28, 61, 56,  5, 32, 74, 94, 32],
       [91, 25, 71, 17, 18, 95, 86, 61, 70, 97]])

In [16]:
randMatrixB

array([[65,  1,  1, 80, 69, 90, 48,  4, 53,  5],
       [35, 82, 43, 57, 80, 55, 97, 25, 96, 24],
       [27, 89, 99, 27, 72, 32, 70, 68, 45, 72],
       [91, 64, 99, 82, 77, 94, 24, 91,  4, 22],
       [14, 61,  9, 20, 32, 88, 15, 71, 38, 49],
       [82, 92, 83, 10, 28, 94, 84, 53, 38, 53],
       [82, 53, 28, 75, 95, 70,  1, 86, 21, 14],
       [ 2, 99,  6, 86, 90, 47, 61, 22, 12, 60],
       [87, 58, 83, 19, 78, 43, 89, 95,  3, 23],
       [31, 51, 25, 46, 74,  9, 94, 26, 31, 98]])

In [17]:
# Concatenate one block on another
np.concatenate([randMatrixA, randMatrixB], axis=0)

array([[17, 81, 86,  4, 93, 40, 37, 19, 65, 12],
       [64, 21, 26, 55, 54, 76, 14,  9, 36, 90],
       [80, 79, 76, 96, 20, 36, 15, 24, 66, 91],
       [32, 71, 32, 32, 10, 76, 48, 50, 11, 11],
       [55, 28, 91, 54, 40, 48, 89, 90, 46, 35],
       [42, 64, 21, 93, 38, 85, 15, 80, 49, 13],
       [84, 61, 67, 48, 80,  7,  2, 32, 95, 16],
       [65, 19, 92,  8, 23, 27,  7, 52, 22, 81],
       [85, 38, 28, 61, 56,  5, 32, 74, 94, 32],
       [91, 25, 71, 17, 18, 95, 86, 61, 70, 97],
       [65,  1,  1, 80, 69, 90, 48,  4, 53,  5],
       [35, 82, 43, 57, 80, 55, 97, 25, 96, 24],
       [27, 89, 99, 27, 72, 32, 70, 68, 45, 72],
       [91, 64, 99, 82, 77, 94, 24, 91,  4, 22],
       [14, 61,  9, 20, 32, 88, 15, 71, 38, 49],
       [82, 92, 83, 10, 28, 94, 84, 53, 38, 53],
       [82, 53, 28, 75, 95, 70,  1, 86, 21, 14],
       [ 2, 99,  6, 86, 90, 47, 61, 22, 12, 60],
       [87, 58, 83, 19, 78, 43, 89, 95,  3, 23],
       [31, 51, 25, 46, 74,  9, 94, 26, 31, 98]])

In [18]:
# Concatenate
np.concatenate([randMatrixA, randMatrixB], axis=1)



array([[17, 81, 86,  4, 93, 40, 37, 19, 65, 12, 65,  1,  1, 80, 69, 90,
        48,  4, 53,  5],
       [64, 21, 26, 55, 54, 76, 14,  9, 36, 90, 35, 82, 43, 57, 80, 55,
        97, 25, 96, 24],
       [80, 79, 76, 96, 20, 36, 15, 24, 66, 91, 27, 89, 99, 27, 72, 32,
        70, 68, 45, 72],
       [32, 71, 32, 32, 10, 76, 48, 50, 11, 11, 91, 64, 99, 82, 77, 94,
        24, 91,  4, 22],
       [55, 28, 91, 54, 40, 48, 89, 90, 46, 35, 14, 61,  9, 20, 32, 88,
        15, 71, 38, 49],
       [42, 64, 21, 93, 38, 85, 15, 80, 49, 13, 82, 92, 83, 10, 28, 94,
        84, 53, 38, 53],
       [84, 61, 67, 48, 80,  7,  2, 32, 95, 16, 82, 53, 28, 75, 95, 70,
         1, 86, 21, 14],
       [65, 19, 92,  8, 23, 27,  7, 52, 22, 81,  2, 99,  6, 86, 90, 47,
        61, 22, 12, 60],
       [85, 38, 28, 61, 56,  5, 32, 74, 94, 32, 87, 58, 83, 19, 78, 43,
        89, 95,  3, 23],
       [91, 25, 71, 17, 18, 95, 86, 61, 70, 97, 31, 51, 25, 46, 74,  9,
        94, 26, 31, 98]])